apiVersion: batch/v1
kind: Job
metadata:
  name: manual-train-weather-predictor
spec:
  template:
    spec:
      containers:
        - name: train-weather-predictor
          image: undercoverducky/train-weather-prediction:0.0.5-amd64
          command: [ "python", "/code/train_weather_predictor.py" ]
          #resources:
          #  limits:
          #    nvidia.com/gpu: 1
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
      restartPolicy: OnFailure
      nodeSelector:
        nodegroup: seldon-test-frontend-dev