apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightly-collect-weather-metrics
spec:
  schedule: "0 0 * * *"  # This cron schedule translates to every night at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: collect-weather-metrics
              image: undercoverducky/weathermetriccollection:0.0.7-amd64
              command: [ "python", "/code/collect_metrics.py" ]
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_SECRET_ACCESS_KEY
          restartPolicy: OnFailure
          nodeSelector:
            nodegroup: seldon-test-frontend-dev
