apiVersion: batch/v1
kind: CronJob
metadata:
  name: collect-training-data
spec:
  schedule: "0 0 10 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: collect-training-data
              image: undercoverducky/weatherdatacollection:0.0.1-amd64
              command: [ "python", "/code/collect_training_data.py" ]
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_SECRET_ACCESS_KEY
          restartPolicy: OnFailure
          nodeSelector:
            nodegroup: seldon-test-frontend-dev